### ISSUE TITLE
In minimization.py def D_p(label, graph, x, y) returns always zero  

### ISSUE THREAD

**Issue by AleUriel** [roflmaostc/Fast-Approximate-Energy-Minimization-via-Graph-Cuts#1]
Hi! the function def D_p(label, graph, x, y) always returns zero because the input label and graph are the same.
This function is used inside  - def calculate_energy(img_orig, img_work) - 

```
def calculate_energy(img_orig, img_work):
    '''Calculates Energy of image.
       img: is input array'''

    E_data = 0
    for i in range(len(img_orig)):
        for j in range(len(img_orig[0])):
            E_data += D_p(img_orig[i][j], img_work, j, i)``
```

Can you help me? Thanks!

**Comment by roflmaostc** [comment]
Hey,

disclaimer: that's quite an old code from an early stage of my programming career :joy: 

I guess D_p is not always zero. It's just zero when `label` and `graph[y][x]` are the same.
`label` is just a number, whereas `graph` is a array. And then we simply add a penalty once `graph[y][x] != label`.

```
        t_weight_alpha = sum([V_p_q(alpha,v) for v in fil_neigh]) + D_p(alpha, img_orig, x, y)
        t_weight_beta = sum([V_p_q(beta,v) for v in fil_neigh]) + D_p(beta, img_orig, x, y)
```
As long as `beta != alpha` `D_p` won't be zero for all inputs, right?

Cheers,

Felix

**Comment by AleUriel** [comment]
Hi! Thanks for the reply

i understand. I have this issue because i have a problem to import **maxflow** , so i 'm trying the code func by func without  **maxflow**  and i had that problem.

Thanks again
